/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

const bcrypt = require("bcrypt");

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();

  const password = await bcrypt.hash("password123", 10);

  await knex("users").insert([
    {
      email: "john@test.com",
      first_name: "John",
      last_name: "Johnson",
      phone_number: "5551234567",
      zip_code: "02780",
      city: "Taunton",
      state: "MA",
      lat: 41.905,
      lng: -71.1026,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "bob@test.com",
      first_name: "Bob",
      last_name: "Smith",
      phone_number: "5559876543",
      zip_code: "02301",
      city: "Brockton",
      state: "MA",
      lat: 42.0794,
      lng: -71.04,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "alice@test.com",
      first_name: "Alice",
      last_name: "Williams",
      phone_number: "5551112222",
      zip_code: "02780",
      city: "Taunton",
      state: "MA",
      lat: 41.908,
      lng: -71.1015,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "carol@test.com",
      first_name: "Carol",
      last_name: "Brown",
      phone_number: "5553334444",
      zip_code: "02780",
      city: "Taunton",
      state: "MA",
      lat: 41.902,
      lng: -71.1035,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "dave@test.com",
      first_name: "Dave",
      last_name: "Davis",
      phone_number: "5555556666",
      zip_code: "02780",
      city: "Taunton",
      state: "MA",
      lat: 41.907,
      lng: -71.101,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "eve@test.com",
      first_name: "Eve",
      last_name: "Miller",
      phone_number: "5557778888",
      zip_code: "02780",
      city: "Taunton",
      state: "MA",
      lat: 41.904,
      lng: -71.105,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "frank@test.com",
      first_name: "Frank",
      last_name: "Taylor",
      phone_number: "5559998888",
      zip_code: "02767",
      city: "Raynham",
      state: "MA",
      lat: 41.95,
      lng: -71.125,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "grace@test.com",
      first_name: "Grace",
      last_name: "Anderson",
      phone_number: "5551231234",
      zip_code: "02368",
      city: "Easton",
      state: "MA",
      lat: 42.0,
      lng: -71.12,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "henry@test.com",
      first_name: "Henry",
      last_name: "Thomas",
      phone_number: "5554564567",
      zip_code: "02134",
      city: "Boston",
      state: "MA",
      lat: 42.365,
      lng: -71.165,
      password_digest: password,
      profile_image: null,
    },
    {
      email: "iris@test.com",
      first_name: "Iris",
      last_name: "Jackson",
      phone_number: "5557897890",
      zip_code: "06510",
      city: "New Haven",
      state: "CT",
      lat: 41.31,
      lng: -72.92,
      password_digest: password,
      profile_image: null,
    },
  ]);
};
